package view;

import java.awt.Color;
import java.awt.Component;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

import projekt.ATableModel;
import projekt.OFOTableModel;
import projekt.ProductOrder;
import projekt.ProductQuantity;
import projekt.STableModel;
import projekt.StorageMainPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Maciej
 */
public class JFrameStorage extends javax.swing.JFrame {

	StorageMainPanel SMP;

	/**
	 * Creates new form JFrame
	 */
	public JFrameStorage(StorageMainPanel storageMainPanel) {
		SMP = storageMainPanel;
		initComponents();
		setVisible(true);
		tOrdersFromOutside.setModel(new OFOTableModel(SMP.getOFO()));
		tStorage.setModel(new STableModel(SMP.getStorage()));
		tArchive.setModel(new ATableModel(SMP.getArchive()));
		OFO.setVisible(true);
		Storage.setVisible(false);
		Archive.setVisible(false);
		checkColors();
	}

	private void checkColors() {
		tStorage.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
			@Override
			public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected,
					boolean hasFocus, int row, int col) {

				super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);

				int q = (int) table.getModel().getValueAt(row, 3);
				if (!isSelected) {
					if (q < 10 && q > 5) {
						setBackground(Color.YELLOW);
					} else if (q <= 5 && q > 0) {
						setBackground(Color.RED);
					} else if (q == 0) {
						setBackground(Color.GRAY);
					} else {
						setBackground(table.getBackground());
						setForeground(table.getForeground());
					}
				}
				return this;
			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		OFO = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tOrdersFromOutside = new javax.swing.JTable();
		bOFOClose = new javax.swing.JButton();
		bOFOShowArchive = new javax.swing.JButton();
		bOFOShowStorage = new javax.swing.JButton();
		bOFORefresh = new javax.swing.JButton();
		bOFOExecute = new javax.swing.JButton();
		Storage = new javax.swing.JPanel();
		bSRefresh = new javax.swing.JButton();
		bSClose = new javax.swing.JButton();
		bSShowOFO = new javax.swing.JButton();
		bSShowArchive = new javax.swing.JButton();
		bSOrder = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		tStorage = new javax.swing.JTable();
		jLabel1 = new javax.swing.JLabel();
		txtSHowMuch = new javax.swing.JTextField();
		Archive = new javax.swing.JPanel();
		jScrollPane3 = new javax.swing.JScrollPane();
		tArchive = new javax.swing.JTable();
		bAShowOFO = new javax.swing.JButton();
		bAShowArchive = new javax.swing.JButton();
		bARefresh = new javax.swing.JButton();
		bAClose = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Magazyn");

		OFO.setName("Magazyn"); // NOI18N

		tOrdersFromOutside.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] {

		}));
		jScrollPane1.setViewportView(tOrdersFromOutside);

		bOFOClose.setText("Zamknij");
		bOFOClose.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bOFOCloseActionPerformed(evt);
			}
		});

		bOFOShowArchive.setText("Wyœwietl Archiwum");
		bOFOShowArchive.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bOFOShowArchiveActionPerformed(evt);
			}
		});

		bOFOShowStorage.setText("Wyœwietl Magazyn");
		bOFOShowStorage.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bOFOShowStorageActionPerformed(evt);
			}
		});

		bOFORefresh.setText("Odœwie¿");
		bOFORefresh.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bOFORefreshActionPerformed(evt);
			}
		});

		bOFOExecute.setText("Wykonaj zamówienie");
		bOFOExecute.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bOFOExecuteActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout OFOLayout = new javax.swing.GroupLayout(OFO);
		OFO.setLayout(OFOLayout);
		OFOLayout.setHorizontalGroup(OFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(OFOLayout.createSequentialGroup()
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(OFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(bOFOShowStorage, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(bOFOShowArchive, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(bOFORefresh, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(bOFOExecute, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
								.addComponent(bOFOClose, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(0, 22, Short.MAX_VALUE)));
		OFOLayout.setVerticalGroup(OFOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						OFOLayout.createSequentialGroup().addContainerGap().addComponent(bOFOExecute)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(bOFORefresh)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(bOFOShowStorage)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(bOFOShowArchive).addGap(4, 4, 4).addComponent(bOFOClose)
								.addGap(22, 22, 22)));

		bSRefresh.setText("Odœwie¿");
		bSRefresh.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bSRefreshActionPerformed(evt);
			}
		});

		bSClose.setText("Zamknij");
		bSClose.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bSCloseActionPerformed(evt);
			}
		});

		bSShowOFO.setText("Wyœwietl Zamówienia");
		bSShowOFO.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bSShowOFOActionPerformed(evt);
			}
		});

		bSShowArchive.setText("Wyœwietl Archiwum");
		bSShowArchive.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bSShowArchiveActionPerformed(evt);
			}
		});

		bSOrder.setText("Zamów produkt");
		bSOrder.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bSOrderActionPerformed(evt);
			}
		});

		tStorage.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] {

		}));
		jScrollPane2.setViewportView(tStorage);

		jLabel1.setText("x");

		javax.swing.GroupLayout StorageLayout = new javax.swing.GroupLayout(Storage);
		Storage.setLayout(StorageLayout);
		StorageLayout.setHorizontalGroup(StorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(StorageLayout.createSequentialGroup()
						.addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 513,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(StorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(bSShowOFO, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
								.addComponent(bSShowArchive, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(bSRefresh, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(bSClose, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(StorageLayout.createSequentialGroup().addComponent(bSOrder).addGap(5, 5, 5)
										.addComponent(jLabel1).addGap(5, 5, 5).addComponent(txtSHowMuch)))
						.addGap(0, 32, Short.MAX_VALUE)));
		StorageLayout.setVerticalGroup(StorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StorageLayout.createSequentialGroup()
						.addContainerGap()
						.addGroup(StorageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(bSOrder).addComponent(jLabel1).addComponent(txtSHowMuch,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(bSShowOFO).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(bSRefresh).addGap(7, 7, 7).addComponent(bSShowArchive).addGap(4, 4, 4)
						.addComponent(bSClose).addGap(22, 22, 22)));

		tArchive.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {

		}, new String[] {

		}));
		jScrollPane3.setViewportView(tArchive);

		bAShowOFO.setText("Wyœwietl Zamówienia");
		bAShowOFO.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bAShowOFOActionPerformed(evt);
			}
		});

		bAShowArchive.setText("Wyœwietl Magazyn");
		bAShowArchive.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bAShowArchiveActionPerformed(evt);
			}
		});

		bARefresh.setText("Odœwie¿");
		bARefresh.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bARefreshActionPerformed(evt);
			}
		});

		bAClose.setText("Zamknij");
		bAClose.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bACloseActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout ArchiveLayout = new javax.swing.GroupLayout(Archive);
		Archive.setLayout(ArchiveLayout);
		ArchiveLayout.setHorizontalGroup(ArchiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(ArchiveLayout.createSequentialGroup()
						.addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 513,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(ArchiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(bAShowOFO, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
								.addComponent(bAShowArchive, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(bARefresh, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(bAClose, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGap(0, 32, Short.MAX_VALUE)));
		ArchiveLayout
				.setVerticalGroup(
						ArchiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 499,
										Short.MAX_VALUE)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										ArchiveLayout.createSequentialGroup()
												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(bAShowOFO)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(bAShowArchive)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(bARefresh)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(bAClose).addGap(22, 22, 22)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(OFO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(Storage,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(Archive,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(OFO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(Storage,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(Archive,
						javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void bOFOCloseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bOFOCloseActionPerformed
		if (this.isDisplayable()) {
			this.dispose();
		}
	}// GEN-LAST:event_bOFOCloseActionPerformed

	private void bOFORefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bOFORefreshActionPerformed
		SMP.archive.refresh();
		tOrdersFromOutside.setModel(new OFOTableModel(SMP.getOFO()));
	}// GEN-LAST:event_bOFORefreshActionPerformed

	private void bOFOExecuteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bOFOExecuteActionPerformed
		if (tOrdersFromOutside.getSelectedRow() != -1) {
			ProductOrder p = SMP.getOFO().get(tOrdersFromOutside.getSelectedRow());

			if (p.from.equals("Sklep") && p.to.equals("Magazyn")) {
				SMP.ordersFromOutside.remove(p);
				SMP.takeIn(p.productQuantity, p.from);
				// ((OFOTableModel)
				// tOrdersFromOutside.getModel()).removeRow(tOrdersFromOutside.getSelectedRow());
			} else {
				if (SMP.storage.getStorage(p.productQuantity.product.id)
						.get(0).quantity >= p.productQuantity.quantity) {
					SMP.ordersFromOutside.remove(p);
					SMP.giveOut(p.productQuantity, p.from);
					// ((OFOTableModel)
					// tOrdersFromOutside.getModel()).removeRow(tOrdersFromOutside.getSelectedRow());
				} else {
					ProductOrder pp = new ProductOrder(p.id, p.productQuantity, new Date(), "Magazyn", "Sklep");
					SMP.order(pp, "Sklep");
					((OFOTableModel) tOrdersFromOutside.getModel()).fireTableDataChanged();
					JOptionPane.showMessageDialog(rootPane, "Niewystarczaj¹ca iloœæ produktu. Zamówiono dostawê.");
				}
			}
			tOrdersFromOutside.setModel(new OFOTableModel(SMP.getOFO()));

		}
	}// GEN-LAST:event_bOFOExecuteActionPerformed

	private void bOFOShowStorageActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bOFOShowStorageActionPerformed
		OFO.setVisible(false);
		Storage.setVisible(true);
		((STableModel) tStorage.getModel()).fireTableDataChanged();
		Archive.setVisible(false);
	}// GEN-LAST:event_bOFOShowStorageActionPerformed

	private void bOFOShowArchiveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bOFOShowArchiveActionPerformed
		OFO.setVisible(false);
		Storage.setVisible(false);
		Archive.setVisible(true);
		((ATableModel) tArchive.getModel()).fireTableDataChanged();
	}// GEN-LAST:event_bOFOShowArchiveActionPerformed

	private void bSRefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bSRefreshActionPerformed
		SMP.storage.refresh();
		((OFOTableModel) tOrdersFromOutside.getModel()).fireTableDataChanged();
	}// GEN-LAST:event_bSRefreshActionPerformed

	private void bSCloseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bSCloseActionPerformed
		if (this.isDisplayable()) {
			this.dispose();
		}
	}// GEN-LAST:event_bSCloseActionPerformed

	private void bSShowOFOActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bSShowOFOActionPerformed
		OFO.setVisible(true);
		((OFOTableModel) tOrdersFromOutside.getModel()).fireTableDataChanged();
		Storage.setVisible(false);
		Archive.setVisible(false);
	}// GEN-LAST:event_bSShowOFOActionPerformed

	private void bSShowArchiveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bSShowArchiveActionPerformed
		OFO.setVisible(false);
		Storage.setVisible(false);
		Archive.setVisible(true);
		((ATableModel) tArchive.getModel()).fireTableDataChanged();
	}// GEN-LAST:event_bSShowArchiveActionPerformed

	private void bSOrderActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bSOrderActionPerformed
		// public ProductOrder(String id, ProductQuantity productQuantity, Date
		// date, String from, String to)
		if (tStorage.getSelectedRow() != -1) {
			ProductQuantity p = SMP.getStorage().get(tStorage.getSelectedRow());
			String id = "1";
			if (!SMP.getArchive().isEmpty()) {
				id = Integer.toString(Integer.parseInt(SMP.getArchive().get(SMP.getArchive().size() - 1).id) + 1);
			}
			ProductOrder po = new ProductOrder(id,
					new ProductQuantity(p.product, Integer.parseInt(txtSHowMuch.getText())), new Date(), "Magazyn",
					"Sklep");
			SMP.order(po, "Sklep");
			((STableModel) tStorage.getModel()).fireTableDataChanged();
		}
		txtSHowMuch.setText("");
	}// GEN-LAST:event_bSOrderActionPerformed

	private void bAShowOFOActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bAShowOFOActionPerformed
		OFO.setVisible(true);
		((OFOTableModel) tOrdersFromOutside.getModel()).fireTableDataChanged();
		Storage.setVisible(false);
		Archive.setVisible(false);
	}// GEN-LAST:event_bAShowOFOActionPerformed

	private void bAShowArchiveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bAShowArchiveActionPerformed
		OFO.setVisible(false);
		Storage.setVisible(true);
		((STableModel) tStorage.getModel()).fireTableDataChanged();
		Archive.setVisible(false);
	}// GEN-LAST:event_bAShowArchiveActionPerformed

	private void bARefreshActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bARefreshActionPerformed
		SMP.archive.refresh();
		((ATableModel) tArchive.getModel()).fireTableDataChanged();
	}// GEN-LAST:event_bARefreshActionPerformed

	private void bACloseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bACloseActionPerformed
		if (this.isDisplayable()) {
			this.dispose();
		}
	}// GEN-LAST:event_bACloseActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(JFrameStorage.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(JFrameStorage.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(JFrameStorage.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(JFrameStorage.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				// new JFrame(SMP).setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel Archive;
	private javax.swing.JPanel OFO;
	private javax.swing.JPanel Storage;
	private javax.swing.JButton bAClose;
	private javax.swing.JButton bARefresh;
	private javax.swing.JButton bAShowArchive;
	private javax.swing.JButton bAShowOFO;
	private javax.swing.JButton bOFOClose;
	private javax.swing.JButton bOFOExecute;
	private javax.swing.JButton bOFORefresh;
	private javax.swing.JButton bOFOShowArchive;
	private javax.swing.JButton bOFOShowStorage;
	private javax.swing.JButton bSClose;
	private javax.swing.JButton bSOrder;
	private javax.swing.JButton bSRefresh;
	private javax.swing.JButton bSShowArchive;
	private javax.swing.JButton bSShowOFO;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTable tArchive;
	private javax.swing.JTable tOrdersFromOutside;
	private javax.swing.JTable tStorage;
	private javax.swing.JTextField txtSHowMuch;
	// End of variables declaration//GEN-END:variables
}
